### ISSUE TITLE
missing app "estore"

### ISSUE THREAD

**Issue by caesarleong** [cjltsod/django-spgateway#1]
_ValueError: The field spgateway.SpgatewayNotifyResponseInfo.Order was declared with a lazy reference to 'estore.order', but app 'estore' isn't installed._

facing this error when makemigrations. is it require more app to install? Thanks

**Comment by cjltsod** [comment]
It's shouldn't happened. I am sorry.
I made the fast fix without testing. Have a look at [here](https://github.com/cjltsod/django-spgateway/commit/fb9b3ee752cf5f8152699e491a3267840efa886e)

I'm currently working on an update of this project. It should be arrived very soon.
Don't hesitate to let us know if your issue resolved or not.

**Comment by caesarleong** [comment]
Hi, 
with your quick fix, I see below error
  _File "/home/caesar/Work/myvenv/lib/python3.5/site-packages/spgateway/migrations/0001_initial.py", line 110, in Migration
    ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.SPGATEWAY_ORDERMODEL, verbose_name='訂單')),
NameError: name 'settings' is not defined_

Then added the import (from django.conf import settings) into 0001 migration py. And the error becames
_ValueError: The field spgateway.SpgatewayNotifyResponseInfo.Order was declared with a lazy reference to 'mysite.order', but app 'mysite' isn't installed._

I am sure "mysite” is in the INSTALLED_APPS. Please kindly help to check this issue. Thank you very much.

BTW, I'm now directly copy your source into my project instead of pip install it. and during the integration I met some strange case, is that okay I raise other issue about what I met? Thanks

**Comment by cjltsod** [comment]
I'll have a deep look this weekend. May I have your Django version?
And sure. Feel free to let me know what other issues you've encountered.

**Comment by caesarleong** [comment]
My Django version is 1.11.10, Thanks for your effort!

**Comment by cjltsod** [comment]
Sorry for delay. 
Even using Django 1.11.10 with Python 3.5.5, I still can't re-generate the error you've encountered.
It seems like rename and migration problem during failed migrations. 
Try to empty your database, and migrate again.
Re-open this issue if you still encounter after you empty your database.
