### ISSUE TITLE
missing models SpgatewayCustomerResponseATM

### ISSUE THREAD

**Issue by caesarleong** [cjltsod/django-spgateway#3]
SpgatewayCustomerResponseATM is used in SpgatewayCustomerView but it is not exist. I think it should be SpgatewayCustomerResponseVACC.

**Comment by caesarleong** [comment]
extend this issue, class SpgatewayResonseViewMixin post method will have problem if using customerResponseInfo. So I added a check before create object like below code:

            if ('/customer/' in request.path):
                object = models.SpgatewayCustomerResponseInfo()
            else:
                object = models.SpgatewayNotifyResponseInfo()

Not sure this is a good fix, but at least it's work for me. ^_^

**Comment by cjltsod** [comment]
Hmmmm..... I miss this part.
I'll implement CustomerResponse part soon.
